language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t matrodaff/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true matrodaff/react-test npm test

after_success:
  - docker build -t matrodaff/muilt-client ./client
  - docker build -t matrodaff/muilt-nginx ./nginx
  - docker build -t matrodaff/muilt-server ./server
  - docker build -t matrodaff/muilt-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push matrodaff/muilt-client
  - docker push matrodaff/muilt-nginx
  - docker push matrodaff/muilt-server
  - docker push matrodaff/muilt-worker
  